import { createContext, useContext, useState, ReactNode } from "react";

type Lang = "NL" | "DE" | "FR" | "EN";

const translations: Record<Lang, Record<string, string>> = {
  NL: {
    // Nav
    "nav.about": "Over Ons",
    "nav.services": "Diensten",
    "nav.contact": "Contact",
    "nav.search": "Zoek producten, medicijnen, hulpmiddelen...",

    // Hero
    "hero.badge": "GDP & WDA Gecertificeerd",
    "hero.desc": "Belgomed BV: Uw vertrouwde medische groothandel met GDP en WDA vergunning. Kwaliteit, compliance en betrouwbare distributie.",
    "hero.cta": "Onze Diensten",
    "hero.contact": "Contact",

    // Stats
    "stats.products": "medische hulpmiddelen in voorraad",
    "stats.deliveries": "leveringen per jaar",
    "stats.clients": "ziekenhuizen, rusthuizen & apothekers",
    "stats.team": "collega's die voor je klaarstaan",

    // About
    "about.tag": "Onze Expertise",
    "about.title": "Jouw partner voor een\nzorgeloos medicijnbeheer",
    "about.p1": "In de zorg is een goed gevulde voorraad medicijnen cruciaal. Tekorten leiden niet alleen tot uitgestelde behandelingen, maar verhogen ook de druk op zorgverleners en brengen extra risico's voor patiënten met zich mee. Belgomed BV helpt dit te voorkomen door apotheken, ziekenhuizen en andere zorginstellingen te voorzien van de juiste producten, met stabiele leveringen, concurrerende prijzen en volledig beheer van logistiek en administratie.",
    "about.p2": "Zo kunnen zorgverleners zich concentreren op wat écht telt: het welzijn van hun patiënten. We werken nauw samen met onze klanten en logistieke partners om processen efficiënt en betrouwbaar te laten verlopen. Met een strakke planning, een goedgevulde voorraad en doelgerichte oplossingen zorgen we dat medicijnen en medische hulpmiddelen altijd beschikbaar zijn.",
    "about.cta": "Neem Contact Op",
    "about.location": "Hasselt, BE",
    "about.locationSub": "Logistiek Zenuwcentrum",

    // Sectors
    "sectors.tag": "Wie We Bedienen",
    "sectors.title": "Onze Sectoren",
    "sector.pharmacies": "Apotheken",
    "sector.hospitals": "Ziekenhuizen",
    "sector.care": "Woonzorgcentra",
    "sector.psychiatric": "Psychiatrische instellingen",
    "sector.polyclinic": "Polikliniek",
    "sector.ngo": "NGO",

    // Services section (diensten)
    "diensten.tag": "Wat Wij Doen",
    "diensten.title": "Onze Diensten",
    "dienst.1.title": "Snelle landelijke distributie",
    "dienst.1.desc": "In heel België zorgen wij voor een snelle en veilige levering van medicijnen.",
    "dienst.2.title": "Stockbeheer met reserve",
    "dienst.2.desc": "Met een efficiënt stockbeheer en een noodreserve voorkomen wij tekorten, ook in crisissituaties.",
    "dienst.3.title": "Groepsaankoop en betere voorwaarden",
    "dienst.3.desc": "Door een gezamenlijke aankoop bieden wij zorginstellingen betere voorwaarden en lagere kosten.",
    "dienst.4.title": "Geoptimaliseerde processen",
    "dienst.4.desc": "We nemen logistieke en administratieve taken uit handen, zodat zorgverleners meer ruimte krijgen om zich op patiënten te focussen.",
    "dienst.5.title": "Innovatieve oplossingen voor de zorg",
    "dienst.5.desc": "Met innovatieve tools maken wij ons voorraadbeheer en distributie sneller, transparanter en betrouwbaarder.",
    "dienst.6.title": "Administratieve ontzorging",
    "dienst.6.desc": "Wij nemen administratieve taken rondom medicijnbeheer en bestellingen uit handen, zodat zorgverleners zich volledig kunnen concentreren op hun patiënten.",

    // ServiceGrid
    "sg.tag": "Onze Diensten",
    "sg.title1": "Volledige Farmaceutische",
    "sg.title2": "Distributie",
    "sg.rx.title": "Medicijnen op Voorschrift",
    "sg.rx.desc": "Veilige en hoogwaardige distributie van voorschriftgeneesmiddelen. Gegarandeerde traceerbaarheid en cold-chain compliance voor alle farmaceutische producten.",
    "sg.otc.title": "OTC Producten",
    "sg.otc.desc": "Breed assortiment vrij verkrijgbare geneesmiddelen. Van pijnstillers tot vitaminen — snel en betrouwbaar geleverd aan apotheken en zorgverleners.",
    "sg.med.title": "Medische Hulpmiddelen",
    "sg.med.desc": "Uitgebreid aanbod klinische benodigdheden en medische apparatuur. CE-gecertificeerde producten met volledige documentatie en technische ondersteuning.",

    // Contact
    "contact.title": "Offerte",
    "contact.titleAccent": "Aanvragen",
    "contact.subtitle": "Vraag een GDP-gecertificeerde offerte aan. Wij nemen binnen 24 uur contact op.",
    "contact.address": "Adres",
    "contact.email": "E-mail",
    "contact.phone": "Telefoon",
    "contact.name": "Naam / Bedrijf *",
    "contact.namePlaceholder": "Uw naam of bedrijfsnaam",
    "contact.emailLabel": "E-mail *",
    "contact.emailPlaceholder": "uw@email.be",
    "contact.phoneLabel": "Telefoon",
    "contact.phonePlaceholder": "+32 ...",
    "contact.productGroup": "Productgroep *",
    "contact.selectType": "Selecteer type...",
    "contact.subject": "Onderwerp *",
    "contact.subjectPlaceholder": "Bijv. Offerte antibiotica DRC",
    "contact.message": "Bericht *",
    "contact.messagePlaceholder": "Beschrijf uw aanvraag...",
    "contact.submit": "Verstuur naar Belgomed Admin",
    "contact.submitting": "Verzenden...",
    "contact.serviceRx": "Medicijnen op voorschrift (RX)",
    "contact.serviceOtc": "OTC / Vrije verkoop",
    "contact.serviceMed": "Medische Hulpmiddelen",
    "contact.success": "Aanvraag verzonden ✓",
    "contact.successDesc": "Uw offerte-aanvraag is ontvangen. We nemen spoedig contact op.",
    "contact.error": "Fout",
    "contact.errorDesc": "Er ging iets mis. Probeer het opnieuw.",
    "contact.errorConnection": "Verbindingsfout. Probeer het later opnieuw.",

    // Footer
    "footer.desc": "Belgomed BV — Uw vertrouwde partner voor farmaceutische distributie met volledige GDP en WDA compliance.",
    "footer.nav": "Navigatie",
    "footer.contact": "Contact",
    "footer.rights": "Alle rechten voorbehouden.",
    "footer.regulated": "FAGG Gereguleerd · GDP Gecertificeerd · WDA Vergund",

    // Timeline
    "timeline.1974": "Oprichting",
    "timeline.1974.desc": "Belgomed wordt opgericht als farmaceutische groothandel in België.",
    "timeline.1990": "Internationale Expansie",
    "timeline.1990.desc": "Start van export naar Centraal-Afrika en het Midden-Oosten.",
    "timeline.2005": "GDP-Certificering",
    "timeline.2005.desc": "Officiële GDP-certificering voor farmaceutische distributie.",
    "timeline.2015": "WDA-Vergunning",
    "timeline.2015.desc": "Verkrijging van de Wholesale Distribution Authorisation.",
    "timeline.now": "Marktleider",
    "timeline.now.desc": "45+ jaar ervaring, opererend vanuit ons distributiecentrum in Hasselt.",
  },

  EN: {
    "nav.about": "About Us",
    "nav.services": "Services",
    "nav.contact": "Contact",
    "nav.search": "Search products, medicines, medical devices...",
    "hero.badge": "GDP & WDA Certified",
    "hero.desc": "Belgomed BV: Your trusted pharmaceutical wholesaler with GDP and WDA authorization. Quality, compliance and reliable distribution.",
    "hero.cta": "Our Services",
    "hero.contact": "Contact",
    "stats.products": "medical devices in stock",
    "stats.deliveries": "deliveries per year",
    "stats.clients": "hospitals, care homes & pharmacies",
    "stats.team": "colleagues at your service",
    "about.tag": "Our Expertise",
    "about.title": "Your partner for\neffortless medicine management",
    "about.p1": "In healthcare, a well-stocked supply of medicines is crucial. Shortages not only delay treatments but also increase pressure on healthcare providers and bring additional risks for patients. Belgomed BV helps prevent this by supplying pharmacies, hospitals and other healthcare institutions with the right products, with stable deliveries, competitive prices and full management of logistics and administration.",
    "about.p2": "This allows healthcare providers to focus on what truly matters: the well-being of their patients. We work closely with our clients and logistics partners to ensure efficient and reliable processes. With precise planning, well-stocked inventory and targeted solutions, we ensure medicines and medical devices are always available.",
    "about.cta": "Get in Touch",
    "about.location": "Hasselt, BE",
    "about.locationSub": "Logistics Hub",
    "sectors.tag": "Who We Serve",
    "sectors.title": "Our Sectors",
    "sector.pharmacies": "Pharmacies",
    "sector.hospitals": "Hospitals",
    "sector.care": "Care Homes",
    "sector.psychiatric": "Psychiatric Institutions",
    "sector.polyclinic": "Polyclinics",
    "sector.ngo": "NGOs",
    "diensten.tag": "What We Do",
    "diensten.title": "Our Services",
    "dienst.1.title": "Fast national distribution",
    "dienst.1.desc": "Throughout Belgium, we ensure fast and safe delivery of medicines.",
    "dienst.2.title": "Stock management with reserve",
    "dienst.2.desc": "With efficient stock management and emergency reserves, we prevent shortages, even in crisis situations.",
    "dienst.3.title": "Group purchasing & better terms",
    "dienst.3.desc": "Through joint purchasing, we offer healthcare institutions better terms and lower costs.",
    "dienst.4.title": "Optimized processes",
    "dienst.4.desc": "We handle logistics and administrative tasks so healthcare providers have more time to focus on patients.",
    "dienst.5.title": "Innovative healthcare solutions",
    "dienst.5.desc": "With innovative tools, we make our inventory management and distribution faster, more transparent and more reliable.",
    "dienst.6.title": "Administrative relief",
    "dienst.6.desc": "We handle administrative tasks around medicine management and orders, so healthcare providers can fully focus on their patients.",
    "sg.tag": "Our Services",
    "sg.title1": "Complete Pharmaceutical",
    "sg.title2": "Distribution",
    "sg.rx.title": "Prescription Medicines",
    "sg.rx.desc": "Safe and high-quality distribution of prescription medicines. Guaranteed traceability and cold-chain compliance for all pharmaceutical products.",
    "sg.otc.title": "OTC Products",
    "sg.otc.desc": "Wide range of over-the-counter medicines. From painkillers to vitamins — delivered quickly and reliably to pharmacies and healthcare providers.",
    "sg.med.title": "Medical Devices",
    "sg.med.desc": "Extensive range of clinical supplies and medical equipment. CE-certified products with complete documentation and technical support.",
    "contact.title": "Request a",
    "contact.titleAccent": "Quote",
    "contact.subtitle": "Request a GDP-certified quote. We will contact you within 24 hours.",
    "contact.address": "Address",
    "contact.email": "Email",
    "contact.phone": "Phone",
    "contact.name": "Name / Company *",
    "contact.namePlaceholder": "Your name or company",
    "contact.emailLabel": "Email *",
    "contact.emailPlaceholder": "your@email.com",
    "contact.phoneLabel": "Phone",
    "contact.phonePlaceholder": "+32 ...",
    "contact.productGroup": "Product Group *",
    "contact.selectType": "Select type...",
    "contact.subject": "Subject *",
    "contact.subjectPlaceholder": "E.g. Quote antibiotics",
    "contact.message": "Message *",
    "contact.messagePlaceholder": "Describe your request...",
    "contact.submit": "Send to Belgomed",
    "contact.submitting": "Sending...",
    "contact.serviceRx": "Prescription Medicines (RX)",
    "contact.serviceOtc": "OTC / Over the Counter",
    "contact.serviceMed": "Medical Devices",
    "contact.success": "Request sent ✓",
    "contact.successDesc": "Your quote request has been received. We will contact you shortly.",
    "contact.error": "Error",
    "contact.errorDesc": "Something went wrong. Please try again.",
    "contact.errorConnection": "Connection error. Please try again later.",
    "footer.desc": "Belgomed BV — Your trusted partner for pharmaceutical distribution with full GDP and WDA compliance.",
    "footer.nav": "Navigation",
    "footer.contact": "Contact",
    "footer.rights": "All rights reserved.",
    "footer.regulated": "FAMHP Regulated · GDP Certified · WDA Authorized",
    "timeline.1974": "Founded",
    "timeline.1974.desc": "Belgomed is founded as a pharmaceutical wholesaler in Belgium.",
    "timeline.1990": "International Expansion",
    "timeline.1990.desc": "Start of export to Central Africa and the Middle East.",
    "timeline.2005": "GDP Certification",
    "timeline.2005.desc": "Official GDP certification for pharmaceutical distribution.",
    "timeline.2015": "WDA Authorization",
    "timeline.2015.desc": "Obtaining the Wholesale Distribution Authorisation.",
    "timeline.now": "Market Leader",
    "timeline.now.desc": "45+ years of experience, operating from our distribution center in Hasselt.",
  },

  FR: {
    "nav.about": "À Propos",
    "nav.services": "Services",
    "nav.contact": "Contact",
    "nav.search": "Rechercher produits, médicaments, dispositifs médicaux...",
    "hero.badge": "Certifié GDP & WDA",
    "hero.desc": "Belgomed BV : Votre grossiste médical de confiance avec autorisation GDP et WDA. Qualité, conformité et distribution fiable.",
    "hero.cta": "Nos Services",
    "hero.contact": "Contact",
    "stats.products": "dispositifs médicaux en stock",
    "stats.deliveries": "livraisons par an",
    "stats.clients": "hôpitaux, maisons de repos & pharmacies",
    "stats.team": "collègues à votre service",
    "about.tag": "Notre Expertise",
    "about.title": "Votre partenaire pour une\ngestion sereine des médicaments",
    "about.p1": "Dans le secteur des soins, un stock bien approvisionné en médicaments est crucial. Les pénuries retardent les traitements, augmentent la pression sur les soignants et engendrent des risques supplémentaires pour les patients. Belgomed BV aide à prévenir cela en fournissant aux pharmacies, hôpitaux et autres établissements de soins les bons produits, avec des livraisons stables, des prix compétitifs et une gestion complète de la logistique et de l'administration.",
    "about.p2": "Ainsi, les soignants peuvent se concentrer sur l'essentiel : le bien-être de leurs patients. Nous collaborons étroitement avec nos clients et partenaires logistiques pour assurer des processus efficaces et fiables. Grâce à une planification rigoureuse et des solutions ciblées, nous garantissons la disponibilité permanente des médicaments et dispositifs médicaux.",
    "about.cta": "Contactez-nous",
    "about.location": "Hasselt, BE",
    "about.locationSub": "Centre Logistique",
    "sectors.tag": "Qui Nous Servons",
    "sectors.title": "Nos Secteurs",
    "sector.pharmacies": "Pharmacies",
    "sector.hospitals": "Hôpitaux",
    "sector.care": "Maisons de repos",
    "sector.psychiatric": "Institutions psychiatriques",
    "sector.polyclinic": "Polycliniques",
    "sector.ngo": "ONG",
    "diensten.tag": "Ce Que Nous Faisons",
    "diensten.title": "Nos Services",
    "dienst.1.title": "Distribution nationale rapide",
    "dienst.1.desc": "Dans toute la Belgique, nous assurons une livraison rapide et sûre des médicaments.",
    "dienst.2.title": "Gestion de stock avec réserve",
    "dienst.2.desc": "Grâce à une gestion efficace des stocks et une réserve d'urgence, nous évitons les pénuries, même en situation de crise.",
    "dienst.3.title": "Achat groupé et meilleures conditions",
    "dienst.3.desc": "Par des achats groupés, nous offrons aux établissements de soins de meilleures conditions et des coûts réduits.",
    "dienst.4.title": "Processus optimisés",
    "dienst.4.desc": "Nous prenons en charge les tâches logistiques et administratives afin que les soignants puissent se concentrer sur leurs patients.",
    "dienst.5.title": "Solutions innovantes pour les soins",
    "dienst.5.desc": "Avec des outils innovants, nous rendons notre gestion des stocks et distribution plus rapide, transparente et fiable.",
    "dienst.6.title": "Décharge administrative",
    "dienst.6.desc": "Nous prenons en charge les tâches administratives liées à la gestion des médicaments et des commandes.",
    "sg.tag": "Nos Services",
    "sg.title1": "Distribution Pharmaceutique",
    "sg.title2": "Complète",
    "sg.rx.title": "Médicaments sur Ordonnance",
    "sg.rx.desc": "Distribution sûre et de haute qualité des médicaments sur ordonnance. Traçabilité garantie et conformité de la chaîne du froid.",
    "sg.otc.title": "Produits OTC",
    "sg.otc.desc": "Large gamme de médicaments en vente libre. Des antidouleurs aux vitamines — livrés rapidement et de manière fiable.",
    "sg.med.title": "Dispositifs Médicaux",
    "sg.med.desc": "Vaste gamme de fournitures cliniques et d'équipements médicaux. Produits certifiés CE avec documentation complète.",
    "contact.title": "Demander un",
    "contact.titleAccent": "Devis",
    "contact.subtitle": "Demandez un devis certifié GDP. Nous vous contacterons dans les 24 heures.",
    "contact.address": "Adresse",
    "contact.email": "E-mail",
    "contact.phone": "Téléphone",
    "contact.name": "Nom / Entreprise *",
    "contact.namePlaceholder": "Votre nom ou entreprise",
    "contact.emailLabel": "E-mail *",
    "contact.emailPlaceholder": "votre@email.be",
    "contact.phoneLabel": "Téléphone",
    "contact.phonePlaceholder": "+32 ...",
    "contact.productGroup": "Groupe de Produits *",
    "contact.selectType": "Sélectionnez le type...",
    "contact.subject": "Sujet *",
    "contact.subjectPlaceholder": "Ex. Devis antibiotiques",
    "contact.message": "Message *",
    "contact.messagePlaceholder": "Décrivez votre demande...",
    "contact.submit": "Envoyer à Belgomed",
    "contact.submitting": "Envoi en cours...",
    "contact.serviceRx": "Médicaments sur ordonnance (RX)",
    "contact.serviceOtc": "OTC / Vente libre",
    "contact.serviceMed": "Dispositifs Médicaux",
    "contact.success": "Demande envoyée ✓",
    "contact.successDesc": "Votre demande de devis a été reçue. Nous vous contacterons rapidement.",
    "contact.error": "Erreur",
    "contact.errorDesc": "Quelque chose s'est mal passé. Réessayez.",
    "contact.errorConnection": "Erreur de connexion. Réessayez plus tard.",
    "footer.desc": "Belgomed BV — Votre partenaire de confiance pour la distribution pharmaceutique avec conformité GDP et WDA complète.",
    "footer.nav": "Navigation",
    "footer.contact": "Contact",
    "footer.rights": "Tous droits réservés.",
    "footer.regulated": "Réglementé AFMPS · Certifié GDP · Autorisé WDA",
    "timeline.1974": "Fondation",
    "timeline.1974.desc": "Belgomed est fondé en tant que grossiste pharmaceutique en Belgique.",
    "timeline.1990": "Expansion Internationale",
    "timeline.1990.desc": "Début des exportations vers l'Afrique centrale et le Moyen-Orient.",
    "timeline.2005": "Certification GDP",
    "timeline.2005.desc": "Certification GDP officielle pour la distribution pharmaceutique.",
    "timeline.2015": "Autorisation WDA",
    "timeline.2015.desc": "Obtention de l'autorisation de distribution en gros.",
    "timeline.now": "Leader du Marché",
    "timeline.now.desc": "45+ ans d'expérience, opérant depuis notre centre de distribution à Hasselt.",
  },

  DE: {
    "nav.about": "Über Uns",
    "nav.services": "Leistungen",
    "nav.contact": "Kontakt",
    "nav.search": "Produkte, Medikamente, Hilfsmittel suchen...",
    "hero.badge": "GDP & WDA Zertifiziert",
    "hero.desc": "Belgomed BV: Ihr vertrauenswürdiger pharmazeutischer Großhändler mit GDP- und WDA-Genehmigung. Qualität, Compliance und zuverlässiger Vertrieb.",
    "hero.cta": "Unsere Leistungen",
    "hero.contact": "Kontakt",
    "stats.products": "medizinische Hilfsmittel auf Lager",
    "stats.deliveries": "Lieferungen pro Jahr",
    "stats.clients": "Krankenhäuser, Pflegeheime & Apotheken",
    "stats.team": "Kollegen für Sie im Einsatz",
    "about.tag": "Unsere Expertise",
    "about.title": "Ihr Partner für ein\nsorgenfreies Medikamentenmanagement",
    "about.p1": "Im Gesundheitswesen ist ein gut gefüllter Medikamentenvorrat entscheidend. Engpässe führen nicht nur zu verzögerten Behandlungen, sondern erhöhen auch den Druck auf Pflegekräfte und bringen zusätzliche Risiken für Patienten mit sich. Belgomed BV hilft dies zu verhindern, indem wir Apotheken, Krankenhäuser und andere Gesundheitseinrichtungen mit den richtigen Produkten versorgen, mit stabilen Lieferungen, wettbewerbsfähigen Preisen und vollständigem Logistik- und Verwaltungsmanagement.",
    "about.p2": "So können sich Pflegekräfte auf das konzentrieren, was wirklich zählt: das Wohlbefinden ihrer Patienten. Wir arbeiten eng mit unseren Kunden und Logistikpartnern zusammen, um effiziente und zuverlässige Prozesse sicherzustellen. Mit präziser Planung und gezielten Lösungen stellen wir sicher, dass Medikamente und medizinische Hilfsmittel immer verfügbar sind.",
    "about.cta": "Kontaktieren Sie Uns",
    "about.location": "Hasselt, BE",
    "about.locationSub": "Logistikzentrum",
    "sectors.tag": "Wen Wir Bedienen",
    "sectors.title": "Unsere Sektoren",
    "sector.pharmacies": "Apotheken",
    "sector.hospitals": "Krankenhäuser",
    "sector.care": "Pflegeheime",
    "sector.psychiatric": "Psychiatrische Einrichtungen",
    "sector.polyclinic": "Polikliniken",
    "sector.ngo": "NGOs",
    "diensten.tag": "Was Wir Tun",
    "diensten.title": "Unsere Leistungen",
    "dienst.1.title": "Schneller nationaler Vertrieb",
    "dienst.1.desc": "In ganz Belgien sorgen wir für eine schnelle und sichere Lieferung von Medikamenten.",
    "dienst.2.title": "Lagerverwaltung mit Reserve",
    "dienst.2.desc": "Mit effizienter Lagerverwaltung und Notreserven verhindern wir Engpässe, auch in Krisensituationen.",
    "dienst.3.title": "Gruppeneinkauf & bessere Konditionen",
    "dienst.3.desc": "Durch gemeinsamen Einkauf bieten wir Gesundheitseinrichtungen bessere Konditionen und niedrigere Kosten.",
    "dienst.4.title": "Optimierte Prozesse",
    "dienst.4.desc": "Wir übernehmen Logistik- und Verwaltungsaufgaben, damit Pflegekräfte mehr Zeit für Patienten haben.",
    "dienst.5.title": "Innovative Lösungen für die Pflege",
    "dienst.5.desc": "Mit innovativen Tools machen wir unser Bestandsmanagement und unseren Vertrieb schneller, transparenter und zuverlässiger.",
    "dienst.6.title": "Administrative Entlastung",
    "dienst.6.desc": "Wir übernehmen administrative Aufgaben rund um Medikamentenmanagement und Bestellungen.",
    "sg.tag": "Unsere Leistungen",
    "sg.title1": "Vollständiger Pharmazeutischer",
    "sg.title2": "Vertrieb",
    "sg.rx.title": "Verschreibungspflichtige Medikamente",
    "sg.rx.desc": "Sichere und hochwertige Distribution verschreibungspflichtiger Medikamente. Garantierte Rückverfolgbarkeit und Cold-Chain-Compliance.",
    "sg.otc.title": "OTC-Produkte",
    "sg.otc.desc": "Breites Sortiment rezeptfreier Medikamente. Von Schmerzmitteln bis Vitaminen — schnell und zuverlässig geliefert.",
    "sg.med.title": "Medizinische Geräte",
    "sg.med.desc": "Umfangreiches Angebot an klinischem Bedarf und medizinischer Ausrüstung. CE-zertifizierte Produkte mit vollständiger Dokumentation.",
    "contact.title": "Angebot",
    "contact.titleAccent": "Anfordern",
    "contact.subtitle": "Fordern Sie ein GDP-zertifiziertes Angebot an. Wir melden uns innerhalb von 24 Stunden.",
    "contact.address": "Adresse",
    "contact.email": "E-Mail",
    "contact.phone": "Telefon",
    "contact.name": "Name / Firma *",
    "contact.namePlaceholder": "Ihr Name oder Firma",
    "contact.emailLabel": "E-Mail *",
    "contact.emailPlaceholder": "ihre@email.be",
    "contact.phoneLabel": "Telefon",
    "contact.phonePlaceholder": "+32 ...",
    "contact.productGroup": "Produktgruppe *",
    "contact.selectType": "Typ auswählen...",
    "contact.subject": "Betreff *",
    "contact.subjectPlaceholder": "Z.B. Angebot Antibiotika",
    "contact.message": "Nachricht *",
    "contact.messagePlaceholder": "Beschreiben Sie Ihre Anfrage...",
    "contact.submit": "An Belgomed senden",
    "contact.submitting": "Wird gesendet...",
    "contact.serviceRx": "Verschreibungspflichtige Medikamente (RX)",
    "contact.serviceOtc": "OTC / Freiverkäuflich",
    "contact.serviceMed": "Medizinische Geräte",
    "contact.success": "Anfrage gesendet ✓",
    "contact.successDesc": "Ihre Angebotsanfrage wurde empfangen. Wir melden uns in Kürze.",
    "contact.error": "Fehler",
    "contact.errorDesc": "Etwas ist schiefgegangen. Bitte versuchen Sie es erneut.",
    "contact.errorConnection": "Verbindungsfehler. Bitte versuchen Sie es später erneut.",
    "footer.desc": "Belgomed BV — Ihr vertrauenswürdiger Partner für pharmazeutischen Vertrieb mit vollständiger GDP- und WDA-Compliance.",
    "footer.nav": "Navigation",
    "footer.contact": "Kontakt",
    "footer.rights": "Alle Rechte vorbehalten.",
    "footer.regulated": "FAGG Reguliert · GDP Zertifiziert · WDA Genehmigt",
    "timeline.1974": "Gründung",
    "timeline.1974.desc": "Belgomed wird als pharmazeutischer Großhändler in Belgien gegründet.",
    "timeline.1990": "Internationale Expansion",
    "timeline.1990.desc": "Beginn des Exports nach Zentralafrika und den Nahen Osten.",
    "timeline.2005": "GDP-Zertifizierung",
    "timeline.2005.desc": "Offizielle GDP-Zertifizierung für pharmazeutischen Vertrieb.",
    "timeline.2015": "WDA-Genehmigung",
    "timeline.2015.desc": "Erhalt der Großhandelsvertriebsgenehmigung.",
    "timeline.now": "Marktführer",
    "timeline.now.desc": "45+ Jahre Erfahrung, betrieben von unserem Distributionszentrum in Hasselt.",
  },
};

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const LangContext = createContext<LangContextType>({
  lang: "NL",
  setLang: () => {},
  t: (key) => key,
});

export const useLang = () => useContext(LangContext);

export const LangProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>("NL");

  const t = (key: string): string => {
    return translations[lang]?.[key] ?? translations.NL[key] ?? key;
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
};
